#!/bin/bash

# Prisma Setup Script for CRM Project

echo "🚀 Starting Prisma Development Setup..."
echo ""
echo "This script will help you set up your Prisma database."
echo ""
echo "Step 1: Start Prisma Dev Server in a new terminal/window"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run this command in terminal 1 (keep it running):"
echo ""
echo "  npx prisma dev"
echo ""
echo "Step 2: Run Migrations"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "In terminal 2 (while terminal 1 is running), run:"
echo ""
echo "  npx prisma migrate dev --name init"
echo ""
echo "Step 3: Generate Prisma Client"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After migrations complete, run:"
echo ""
echo "  npx prisma generate"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Need to inspect your database?"
echo "  npx prisma studio"
echo ""
